version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    groups:
      linting-dx-tools:
        patterns:
          - "*lint*" # eslint, eslint-*, vue-eslint-parser, lint-staged, @commitlint/*, @typescript-eslint/*
          - "prettier"
          - "husky"
          - "@vue/tsconfig"
        update-types:
          - "minor"
          - "patch"
      testing-tools:
        patterns:
          - "vitest"
          - "cypress"
          - "@cypress/*"
          - "@vue/test-utils"
        update-types:
          - "minor"
          - "patch"
